### ISSUE TITLE
Missing filtering options

### ISSUE THREAD

**Issue by husseinalhammad** [PerchCMS/perch-docs#35]
Some filtering options (such as `!in`, `!contains` and `!gt`) are not documented. Some aliases (such as `within`, `is`, `not` and `!eq`) are not documented either.

**Comment by ianhobbs** [comment]
I'd also add `between` is not documented as well.

**Comment by husseinalhammad** [comment]
@ianhobbs `between` and `eqbetween` are already documented for [perch_collection()](https://docs.grabaperch.com/functions/collections/perch-collection/#possible-values-for-match) and [perch_content_custom()](https://docs.grabaperch.com/functions/content/perch-content-custom/#possible-values-for-match). Is there any where else in the docs you think they should be added too?

**Comment by ianhobbs** [comment]
I did eventually find the markup for two values in the match statement here. [Filtering with between](https://docs.grabaperch.com/video/v/filtering-a-region/) It was the comma separated values syntax that I needed for between. Sounds simple when you see it. I have to say I tried every variant imaginable.
